### ISSUE TITLE
crashes with xdist

### ISSUE THREAD

**Issue by remifontan** [willemt/pytest-asyncio-cooperative#19]
I'm encountering  the following issue with `async_cooperative` and `xdist`.

when running the following test with xdist set to more than one proc I get an error:

```python
@pytest.mark.asyncio_cooperative
@pytest.mark.parametrize("numseconds", [3, 2, 1])
async def test_async_xdist(tmp_path, numseconds):
    """
    this is causing issues when calling it with xdist
    """

    print("tmp_path", tmp_path)
    now = time.time()
    print("going to sleep at", now)
    await asyncio.sleep(numseconds)

    elapsed = time.time() - now
    print("done, elapsed", elapsed)
```

error:

```
tests/test_dtaskstuff.py::test_async_xdist[1] 
INTERNALERROR> def worker_internal_error(self, node, formatted_error):
INTERNALERROR>         """
INTERNALERROR>         pytest_internalerror() was called on the worker.
INTERNALERROR>     
INTERNALERROR>         pytest_internalerror() arguments are an excinfo and an excrepr, which can't
INTERNALERROR>         be serialized, so we go with a poor man's solution of raising an exception
INTERNALERROR>         here ourselves using the formatted message.
INTERNALERROR>         """
INTERNALERROR>         self._active_nodes.remove(node)
INTERNALERROR>         try:
INTERNALERROR> >           assert False, formatted_error
INTERNALERROR> E           AssertionError: Traceback (most recent call last):
INTERNALERROR> E               File "pytest/6.2.2/_pytest/main.py", line 269, in wrap_session
INTERNALERROR> E                 session.exitstatus = doit(config, session) or 0
INTERNALERROR> E               File "pytest/6.2.2/_pytest/main.py", line 323, in _main
INTERNALERROR> E                 config.hook.pytest_runtestloop(session=session)
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/hooks.py", line 286, in __call__
INTERNALERROR> E                 return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR> E                 firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/callers.py", line 203, in _multicall
INTERNALERROR> E                 gen.send(outcome)
INTERNALERROR> E               File "pytest-asyncio-cooperative/pytest_asyncio_cooperative/plugin.py", line 308, in pytest_runtestloop
INTERNALERROR> E                 _run_test_loop(tasks, session, run_tests)
INTERNALERROR> E               File "pytest-asyncio-cooperative/pytest_asyncio_cooperative/plugin.py", line 165, in _run_test_loop
INTERNALERROR> E                 loop.run_until_complete(task)
INTERNALERROR> E               File "python3.7/asyncio/base_events.py", line 584, in run_until_complete
INTERNALERROR> E                 return future.result()
INTERNALERROR> E               File "pytest-asyncio-cooperative/pytest_asyncio_cooperative/plugin.py", line 284, in run_tests
INTERNALERROR> E                 item.ihook.pytest_runtest_protocol(item=item, nextitem=None)
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/hooks.py", line 286, in __call__
INTERNALERROR> E                 return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR> E                 firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/callers.py", line 208, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/callers.py", line 80, in get_result
INTERNALERROR> E                 raise ex[1].with_traceback(ex[2])
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/callers.py", line 187, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E               File "pytest/6.2.2/_pytest/runner.py", line 109, in pytest_runtest_protocol
INTERNALERROR> E                 runtestprotocol(item, nextitem=nextitem)
INTERNALERROR> E               File "pytest/6.2.2/_pytest/runner.py", line 120, in runtestprotocol
INTERNALERROR> E                 rep = call_and_report(item, "setup", log)
INTERNALERROR> E               File "pytest/6.2.2/_pytest/runner.py", line 219, in call_and_report
INTERNALERROR> E                 hook.pytest_runtest_logreport(report=report)
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/hooks.py", line 286, in __call__
INTERNALERROR> E                 return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR> E                 firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/callers.py", line 208, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/callers.py", line 80, in get_result
INTERNALERROR> E                 raise ex[1].with_traceback(ex[2])
INTERNALERROR> E               File "pypluggy/0.13.1-py3.1/pluggy/callers.py", line 187, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E               File "pytest_xdist/2.3.0/xdist/remote.py", line 117, in pytest_runtest_logreport
INTERNALERROR> E                 data["item_index"] = self.item_index
INTERNALERROR> E             AttributeError: 'WorkerInteractor' object has no attribute 'item_index'
INTERNALERROR> E           assert False

```

**Comment by willemt** [comment]
pytest-xdist and asyncio-cooperative don't play nicely together, see: https://github.com/willemt/pytest-asyncio-cooperative/issues/10

This error seems different from that old issue so I'll investigate if the situation has changed since.
